patterns:
  - path: "**/*Inputs/**/*.json"
    keys:
      - key: "BlobReferenceProperties.AuthenticationMode"
        working: "ConnectionString"
        committed: "Msi"
      - key: "EventHubProperties.AuthenticationMode"
        working: "ConnectionString"
        committed: "Msi"
      - key: "SqlReferenceProperties.AuthenticationMode"
        working: "ConnectionString"
        committed: "Msi"
    indent: 4

  - path: "**/*Outputs/**/*.json"
    keys:
      - key: "BlobStorageProperties.AuthenticationMode"
        working: "ConnectionString"
        committed: "Msi"
    indent: 4

  - path: "**/JobConfig.json"
    keys:
      - key: "GlobalStorage.AuthenticationMode"
        working: "ConnectionString"
        committed: "Msi"
    indent: 4